Repository LycheeOrg/Lychee, pull requests merged in 2022-09, with the labels that each got.

#1495 fix Installation
  app/Actions/Install/ApplyMigration.php
  app/Actions/Install/DefaultConfig.php
  app/Console/Commands/FixPermissions.php
  app/Exceptions/Handler.php
  app/Exceptions/Handlers/NoEncryptionKey.php
  app/Http/Middleware/Checks/IsInstalled.php
  resources/views/install/permission-line.blade.php
  resources/views/install/permissions.blade.php
  tests/Feature/InstallTest.php
Labels: bug, High Priority

#1505 Fix installation again.
  app/Http/Middleware/Checks/IsInstalled.php
Labels: bug, High Priority

#1508 Ensure that Admin rights are overloading others
  app/Http/Controllers/SessionController.php
  tests/Feature/UsersTest.php
Labels: High Priority

#1512 Fix test generating an error when running without FFMPEG
  tests/Feature/CommandVideoDataTest.php
Labels: Low Priority

#1515 Fixes #1514
  app/Models/Extensions/HasRandomIDAndLegacyTimeBasedID.php
Labels: bug, High Priority

#1480 Shared albums should not consider the `require_link` property.
  app/Policies/AlbumQueryPolicy.php
  tests/Feature/AlbumTest.php
  tests/Feature/GeoDataTest.php
  tests/Feature/PhotosOperationsTest.php
  tests/Feature/SharingSpecialTest.php
  tests/Feature/SharingTestScenariosAbstract.php
  tests/Feature/SharingWithAnonUserAbstract.php
  tests/Feature/SharingWithNonAdminUserAbstract.php
Labels: bug

#1525 Two small (but important) fixes
  app/Http/Livewire/Sidebar.php
  app/Models/BaseAlbumImpl.php
  app/Models/User.php
  composer.lock
  database/migrations/2019_10_03_214750_frame_refresh_in_sec.php
Labels: bug

#1533 version 4.6.1
  database/migrations/2022_09_27_103710_bump_version040601.php
  version.md
Labels: ready4merge
