Repository LycheeOrg/Lychee, pull requests merged in 2023-06, with the labels that each got.

#1875 add support for 418 for dubious queries
  app/Exceptions/Handler.php
  app/Exceptions/HttpHoneyPotException.php
  app/Http/Controllers/HoneyPotController.php
  config/app.php
  config/honeypot.php
  routes/web.php
  tests/Feature/HoneyPotTest.php
Labels: enhancement, Review: easy

#1876 Fixes 1868
  app/Http/Controllers/Administration/SharingController.php
Labels: Review: easy

#1883 Optimizing sql and improved Log data
  app/Actions/Album/SetProtectionPolicy.php
  app/Actions/Album/Unlock.php
  app/Actions/Albums/Top.php
  app/Assets/ArrayToTextTable.php
  app/Contracts/Models/AbstractAlbum.php
  app/DTO/AlbumProtectionPolicy.php
  app/Factories/AlbumFactory.php
  app/Http/Controllers/Administration/SettingsController.php
  app/Http/Requests/Album/GetAlbumRequest.php
  app/Http/Resources/ConfigurationResource.php
  app/Models/BaseAlbumImpl.php
  app/Models/Extensions/BaseAlbum.php
  app/Policies/AlbumPolicy.php
  app/Policies/AlbumQueryPolicy.php
  app/Policies/PhotoPolicy.php
  app/Providers/AppServiceProvider.php
  app/SmartAlbums/BaseSmartAlbum.php
  composer.json
  composer.lock
  tests/Feature/Base/BaseSharingTest.php
  tests/Feature/GeoDataTest.php
  tests/Feature/PhotosOperationsTest.php
  tests/Feature/SmartAlbumVisibilityTest.php
Labels: Review: easy

#1896 Only apply explain when requested
  .env.example
  app/Providers/AppServiceProvider.php
  config/database.php
Labels: High Priority

#1882 Add csp rules for api
  app/Http/Kernel.php
  app/Http/Middleware/DisableCSP.php
  app/Providers/AppServiceProvider.php
  config/secure-headers.php
Labels: Review: easy

#1899 Improved speed on global table
  app/Constants/AccessPermissionConstants.php
  app/Http/Controllers/Administration/DiagnosticsController.php
  app/Http/Controllers/Administration/SharingController.php
  app/Models/Builders/AlbumBuilder.php
  app/Models/User.php
  app/Policies/AlbumQueryPolicy.php
  app/Providers/AppServiceProvider.php
  composer.lock
  database/migrations/2021_12_04_181200_refactor_models.php
  database/migrations/2022_12_12_100000_enable_disable_album_photo_counters.php
  database/migrations/2023_05_15_211448_remove_is_public_album_sorting.php
  database/migrations/2023_06_24_161541_add_indexes.php
  resources/views/access-permissions.blade.php
Labels: Review: medium
