Repository LycheeOrg/Lychee, pull requests merged in 2023-05, with the labels that each got.

#1826 Support very old versions (untestable code)
  app/Legacy/AdminAuthentication.php
Labels: Review: easy, High Priority

#1828 Fix left/right in photo view of tag albums
  app/Http/Resources/Models/TagAlbumResource.php
Labels: Review: easy

#1827 fix api
  app/Http/Resources/Collections/AlbumForestResource.php
  app/Http/Resources/Collections/PositionDataResource.php
  app/Http/Resources/Collections/TopAlbumsResource.php
  app/Http/Resources/ConfigurationResource.php
  app/Http/Resources/InitResource.php
  app/Http/Resources/Models/AlbumResource.php
  app/Http/Resources/Rights/AlbumRightsResource.php
  app/Http/Resources/Rights/GlobalRightsResource.php
  app/Http/Resources/Rights/PhotoRightsResource.php
  app/Http/Resources/Rights/RootAlbumRightsResource.php
  app/Http/Resources/Rights/SettingsRightsResource.php
  app/Http/Resources/Rights/UserManagementRightsResource.php
  app/Http/Resources/Rights/UserRightsResource.php
  app/Http/Resources/SearchResource.php
  app/Http/Resources/Sharing/SharesResource.php
  composer.json
  composer.lock
  config/scramble.php
  routes/api.php
  tests/Feature/LibUnitTests/SessionUnitTest.php
Labels: Review: easy

#1856 Fixes #1855 - update Makefile
  Makefile
  composer.json
Labels: High Priority

#1857 Fix version 4.9 log-viewer paths hard coding
  app/Providers/AppServiceProvider.php
  config/log-viewer.php
  config/secure-headers.php
  database/migrations/2023_05_19_131139_bump_version040901.php
  version.md
Labels: High Priority

#1862 Remove duplicate link. Tweak comment
  app/Providers/AppServiceProvider.php
Labels: Review: easy
