Repository LycheeOrg/Lychee, pull requests merged in 2023-01, with the labels that each got.

#1684 More robust fix on HasAdminUser
  app/Http/Middleware/Checks/HasAdminUser.php
Labels: High Priority

#1691 Fixes #1630 - 2FA not working.
  app/Http/Controllers/WebAuthn/WebAuthnLoginController.php
Labels: High Priority

#1709 Fixes #1703
  tests/Feature/UpdateTest.php
Labels: Review: easy, High Priority

#1708 Setting to make On This Day smart album public
  app/SmartAlbums/OnThisDayAlbum.php
  database/migrations/2023_01_09_133603_public_on_this_day.php
  tests/AbstractTestCase.php
  tests/Feature/Base/BaseSharingTest.php
  tests/Feature/Base/BaseSharingTestScenarios.php
  tests/Feature/Base/BaseSharingWithAnonUser.php
  tests/Feature/Base/BaseSharingWithNonAdminUser.php
  tests/Feature/SharingSpecialTest.php
  tests/Feature/SharingWithAnonUserAndNoPublicSearchTest.php
  tests/Feature/SharingWithAnonUserAndPublicSearchTest.php
  tests/Feature/SharingWithNonAdminUserAndNoPublicSearchTest.php
  tests/Feature/SharingWithNonAdminUserAndPublicSearchTest.php
Labels: Review: easy

#1723 Minor fix in formatting.
  .php-cs-fixer.php
  scripts/gen_release.php
Labels: Review: easy

#1722 Fix sync default user
  app/Console/Commands/Sync.php
Labels: Review: easy

#1724 Add configuration option to set auth guard driver
  .env.example
  config/auth.php
Labels: Review: easy

#1728 Avoid showing errors in tests when they are expected.
  tests/Feature/Traits/CatchFailures.php
Labels: Review: easy

#1733 migrate locales from 'app/Locale/' to 'lang/', drop Lang Facade.
  .php-cs-fixer.php
  app/Contracts/Language.php
  app/Facades/Lang.php
  app/Factories/LangFactory.php
  app/Http/Controllers/SessionController.php
  app/Http/Requests/Settings/SetLangSettingRequest.php
  app/Locale/ChineseSimplified.php
  app/Locale/ChineseTraditional.php
  app/Locale/Czech.php
  app/Locale/Dutch.php
  app/Locale/English.php
  app/Locale/French.php
  app/Locale/German.php
  app/Locale/Greek.php
  app/Locale/Italian.php
  app/Locale/Lang.php
  app/Locale/NorwegianBokmal.php
  app/Locale/Polish.php
  app/Locale/Portuguese.php
  app/Locale/Russian.php
  app/Locale/Slovak.php
  app/Locale/Spanish.php
  app/Locale/Swedish.php
  app/Locale/Vietnamese.php
  app/ModelFunctions/ConfigFunctions.php
  app/Providers/AppServiceProvider.php
  app/SmartAlbums/OnThisDayAlbum.php
  app/SmartAlbums/PublicAlbum.php
  app/SmartAlbums/RecentAlbum.php
  app/SmartAlbums/StarredAlbum.php
  app/SmartAlbums/UnsortedAlbum.php
  config/app.php
  database/migrations/2023_01_25_140614_change-locale.php
  lang/cz/lychee.php
  lang/de/lychee.php
  lang/el/lychee.php
  lang/en/lychee.php
  lang/es/lychee.php
  lang/fr/lychee.php
  lang/it/lychee.php
  lang/nl/lychee.php
  lang/no/lychee.php
  lang/pl/lychee.php
  lang/pt/lychee.php
  lang/ru/lychee.php
  lang/sk/lychee.php
  lang/sv/lychee.php
  lang/vi/lychee.php
  lang/zh_CN/lychee.php
  lang/zh_TW/lychee.php
  resources/views/frontend.blade.php
  resources/views/includes/footer.blade.php
  resources/views/landing.blade.php
  resources/views/layouts/app.blade.php
  tests/Feature/LangTest.php
Labels: Review: easy
