Repository LycheeOrg/Lychee, pull requests merged in 2025-04, with the labels that each got.

#3191 Npm update
  .github/workflows/js_check.yml
  package-lock.json
  package.json
Labels: Review: easy

#3187 Add pdf support.
  resources/js/components/gallery/photoModule/Dock.vue
  resources/js/components/gallery/photoModule/PhotoPanel.vue
  resources/js/composables/photo/basePhoto.ts
Labels: Review: easy

#3190 Fix 500 when opening directly a smart album
  app/ModelFunctions/HasAbstractAlbumProperties.php
Labels: Review: easy, alpha-ready

#3188 Fix 500 on direct photo access without small variants
  app/View/Components/Meta.php
Labels: Review: easy, alpha-ready

#3173 Add easy option to hide the button of help modal in the header
  lang/cz/dialogs.php
  lang/de/dialogs.php
  lang/el/dialogs.php
  lang/en/dialogs.php
  lang/es/dialogs.php
  lang/fr/dialogs.php
  lang/hu/dialogs.php
  lang/it/dialogs.php
  lang/ja/dialogs.php
  lang/nl/dialogs.php
  lang/no/dialogs.php
  lang/pl/dialogs.php
  lang/pt/dialogs.php
  lang/ru/dialogs.php
  lang/sk/dialogs.php
  lang/sv/dialogs.php
  lang/vi/dialogs.php
  lang/zh_CN/dialogs.php
  lang/zh_TW/dialogs.php
  resources/js/components/modals/KeybindingsHelp.vue
Labels: Review: easy, alpha-ready

#3186 Clarify the photo view modes
  resources/js/components/gallery/photoModule/Dock.vue
  resources/js/components/gallery/photoModule/PhotoPanel.vue
  resources/js/composables/photo/basePhoto.ts
Labels: Review: easy, alpha-ready

#3167 Fix parent_album in create album
  app/Http/Requests/Album/AddAlbumRequest.php
  tests/Feature_v2/Album/AlbumCreateTest.php
Labels: Review: easy, alpha-ready

#3169 Fix 500 error when opcache_get_config is not available
  app/Actions/Diagnostics/Pipes/Checks/IniSettingsCheck.php
  app/Actions/Diagnostics/Pipes/Checks/OpCacheCheck.php
  app/Assets/Helpers.php
Labels: Review: easy, alpha-ready

#3201 Fix Webapp debugging.
  app/Http/Middleware/VerifyCsrfToken.php
  config/features.php
  vite.config.ts
Labels: Review: easy

#3208 Fix missing UX: Add key enter to create albums
  resources/js/components/forms/album/AlbumCreateDialog.vue
Labels: Review: easy

#3215 Support 2 different images between protrait and landscape
  app/Http/Resources/GalleryConfigs/LandingPageResource.php
  app/Legacy/V1/Controllers/IndexController.php
  app/Legacy/V1/Resources/ConfigurationResource.php
  app/View/Components/Meta.php
  database/migrations/2025_04_06_200147_portrait_landscape_landing_background.php
  database/migrations/2025_04_06_200737_remove_landing_background.php
  resources/js/lychee.d.ts
  resources/js/views/Landing.vue
Labels: Review: easy

#3166 test: AddAlbumRequestTest
  app/Http/Requests/Album/AddAlbumRequest.php
  app/Http/Requests/Album/MergeAlbumsRequest.php
  tests/Unit/Http/Requests/Album/AddAlbumRequestTest.php
  tests/Unit/Http/Requests/Album/AddTagAlbumRequestTest.php
  tests/Unit/Http/Requests/Album/DeleteAlbumsRequestTest.php
  tests/Unit/Http/Requests/Album/DeleteTrackRequestTest.php
  tests/Unit/Http/Requests/Album/GetAlbumRequestTest.php
  tests/Unit/Http/Requests/Album/MergeAlbumRequestTest.php
Labels: Review: easy

#3219 Add bulk sharing from v4
  lang/cz/sharing.php
  lang/de/sharing.php
  lang/el/sharing.php
  lang/en/sharing.php
  lang/es/sharing.php
  lang/fr/sharing.php
  lang/hu/sharing.php
  lang/it/sharing.php
  lang/ja/sharing.php
  lang/nl/sharing.php
  lang/no/sharing.php
  lang/pl/sharing.php
  lang/pt/sharing.php
  lang/ru/sharing.php
  lang/sk/sharing.php
  lang/sv/sharing.php
  lang/vi/sharing.php
  lang/zh_CN/sharing.php
  lang/zh_TW/sharing.php
  resources/js/components/forms/sharing/BulkSharingModal.vue
  resources/js/style/preset.ts
  resources/js/views/Sharing.vue
Labels: Review: easy

#3218 Do not fetch data from internet when running tests
  app/Metadata/Json/ExternalRequestFunctions.php
Labels: Review: easy

#3233 Fix Settings crash on docker + pgsql setup
  app/Factories/AlbumFactory.php
  app/Http/Controllers/Admin/SettingsController.php
  app/Providers/AppServiceProvider.php
Labels: Review: easy, High Priority

#3242 Fix create tag album modal: close after create, border rounding
  resources/js/components/forms/album/AlbumCreateTagDialog.vue
Labels: Review: easy

#3241 Improve coverage of version controller
  app/Http/Controllers/VersionController.php
  tests/Feature_v2/VersionTest.php
Labels: Review: easy

#3247 Display statistics
  app/Http/Resources/Models/AlbumResource.php
  app/Http/Resources/Models/AlbumStatisticsResource.php
  app/Http/Resources/Models/PhotoResource.php
  app/Http/Resources/Models/PhotoStatisticsResource.php
  app/Http/Resources/Models/SmartAlbumResource.php
  app/Http/Resources/Models/TagAlbumResource.php
  app/Policies/AlbumPolicy.php
  app/Policies/PhotoPolicy.php
  resources/js/components/drawers/PhotoDetails.vue
  resources/js/components/gallery/albumModule/AlbumHero.vue
  resources/js/lychee.d.ts
  resources/js/services/metrics-service.ts
  resources/js/stores/FavouriteState.ts
  resources/js/views/gallery-panels/Album.vue
  resources/js/views/gallery-panels/Search.vue
Labels: Review: easy

#3249 Add quick feedback on top of the job page
  lang/cz/jobs.php
  lang/de/jobs.php
  lang/el/jobs.php
  lang/en/jobs.php
  lang/es/jobs.php
  lang/fr/jobs.php
  lang/hu/jobs.php
  lang/it/jobs.php
  lang/ja/jobs.php
  lang/nl/jobs.php
  lang/no/jobs.php
  lang/pl/jobs.php
  lang/pt/jobs.php
  lang/ru/jobs.php
  lang/sk/jobs.php
  lang/sv/jobs.php
  lang/vi/jobs.php
  lang/zh_CN/jobs.php
  lang/zh_TW/jobs.php
  resources/js/views/Jobs.vue
Labels: Review: easy

#3254 Fix 500 on map and search
  app/Actions/Album/PositionData.php
  app/Actions/Albums/PositionData.php
  app/Actions/Search/PhotoSearch.php
Labels: Review: easy, High Priority

#3253 Refactoring routes files.
  app/Http/Controllers/VueController.php
  app/Http/Middleware/UnlockWithPassword.php
  app/Legacy/V1/Controllers/RedirectController.php
  routes/web_v1.php
  routes/web_v2.php
Labels: Review: easy

#3255 KLO : refactoring for uniformity
  resources/js/components/forms/album/Unlock.vue
  resources/js/components/forms/sharing/ShareLine.vue
  resources/js/components/gallery/albumModule/AlbumHero.vue
  resources/js/components/gallery/albumModule/AlbumPanel.vue
  resources/js/components/gallery/albumModule/thumbs/AlbumThumb.vue
  resources/js/components/gallery/photoModule/NextPrevious.vue
  resources/js/components/gallery/photoModule/PhotoPanel.vue
  resources/js/components/maintenance/DuplicateLine.vue
  resources/js/components/modals/UploadPanel.vue
  resources/js/composables/album/photoActions.ts
  resources/js/composables/contextMenus/contextMenu.ts
  resources/js/composables/photo/getNextPreviousPhoto.ts
  resources/js/composables/photo/photoRoute.ts
  resources/js/router/routes.ts
  resources/js/views/gallery-panels/Album.vue
  resources/js/views/gallery-panels/Albums.vue
  resources/js/views/gallery-panels/Favourites.vue
  resources/js/views/gallery-panels/Frame.vue
  resources/js/views/gallery-panels/Map.vue
  resources/js/views/gallery-panels/Search.vue
Labels: Review: easy

#3258 version 6.5.1 + force cache clear
  database/migrations/2025_04_21_150310_bump_version060501.php
  scripts/gen_release.php
  version.md
Labels: Review: easy, High Priority

#3270 Fix Copy and Tag photo right click operation not working
  resources/js/views/gallery-panels/Album.vue
Labels: Review: easy

#3250 Localization for timeline
  lang/cz/gallery.php
  lang/de/gallery.php
  lang/el/gallery.php
  lang/en/gallery.php
  lang/es/gallery.php
  lang/fr/gallery.php
  lang/hu/gallery.php
  lang/it/gallery.php
  lang/ja/gallery.php
  lang/nl/gallery.php
  lang/no/gallery.php
  lang/pl/gallery.php
  lang/pt/gallery.php
  lang/ru/gallery.php
  lang/sk/gallery.php
  lang/sv/gallery.php
  lang/vi/gallery.php
  lang/zh_CN/gallery.php
  lang/zh_TW/gallery.php
Labels: Review: easy

#3269 Add extensions suggestions and lint on JS side
  .gitignore
  .prettierrc.json
  .vscode/extensions.json
  eslint.config.ts
  package-lock.json
  package.json
  resources/js/components/forms/gallery-dialogs/AlbumMergeDialog.vue
  resources/js/components/forms/gallery-dialogs/MoveDialog.vue
  resources/js/components/forms/search/SearchBox.vue
  resources/js/components/forms/upload/DropBoxChooser.vue
  resources/js/components/forms/upload/UploadingLine.vue
  resources/js/components/statistics/Activity.vue
  resources/js/components/statistics/PunchCard.vue
  resources/js/composables/album/scrollable.ts
  resources/js/composables/album/treeOperations.ts
  resources/js/composables/photo/slideshow.ts
  resources/js/composables/preview/getPreviewInfo.ts
  resources/js/config/csrf-getter.ts
  resources/js/layouts/useGrid.ts
  resources/js/layouts/useMasonry.ts
  resources/js/layouts/useSquare.ts
  resources/js/stores/Auth.ts
  resources/js/vendor/webauthn/webauthn.ts
  resources/js/views/Diagnostics.vue
  resources/js/views/gallery-panels/Frame.vue
  resources/js/views/gallery-panels/Map.vue
Labels: Review: easy

#3262 Fix warnings in route.ts
  resources/js/shims-vue.d.ts
Labels: Review: easy

#3273 Fix taken_at as NaN/NaN/NaN when not existing.
  resources/js/components/drawers/PhotoEdit.vue
Labels: Review: easy

#3263 Allow description to be used in photo thumb (expert setting)
  app/Enum/PhotoThumbInfoType.php
  app/Http/Resources/GalleryConfigs/InitConfig.php
  database/migrations/2025_04_21_185527_config_description_thumbs.php
  resources/js/components/gallery/albumModule/thumbs/PhotoThumb.vue
  resources/js/lychee.d.ts
  resources/js/stores/LycheeState.ts
Labels: Review: easy

#3290 Improve Errors display
  resources/js/views/Error.vue
Labels: Review: easy

#3288 Fixes and minor QoL
  eslint.config.ts
  resources/js/components/gallery/albumModule/AlbumThumbPanel.vue
  resources/js/components/gallery/albumModule/PhotoThumbPanel.vue
  resources/js/components/gallery/albumModule/PhotoThumbPanelList.vue
  resources/js/components/gallery/searchModule/ResultPanel.vue
  resources/js/components/headers/AlbumHeader.vue
  resources/js/components/headers/AlbumsHeader.vue
  resources/js/composables/photo/photoRoute.ts
  resources/js/layouts/PhotoLayout.ts
  resources/js/layouts/getWidth.ts
  resources/js/layouts/useJustify.ts
  resources/js/layouts/useSquare.ts
  resources/js/menus/LeftMenu.vue
  resources/js/views/gallery-panels/Album.vue
  resources/js/views/gallery-panels/Favourites.vue
  resources/js/views/gallery-panels/Frame.vue
  resources/js/views/gallery-panels/Map.vue
  resources/js/views/gallery-panels/Search.vue
Labels: Review: easy, High Priority

#3293 Fix Stats not being saved when uploaded.
  app/Actions/Photo/Create.php
  app/Actions/Photo/Pipes/Shared/SaveStatistics.php
  app/Actions/Photo/Pipes/Shared/SetParentAndOwnership.php
  database/migrations/2025_04_27_153213_fix-stats-missing.php
  database/migrations/2025_04_27_154319_bump_version060503.php
  version.md
Labels: Review: easy, High Priority
